### ISSUE TITLE
Errors with minified versions of plugin

### ISSUE THREAD

**Issue by mauloop** [joshuafontany/TW5-jsoneditor#2]
I would like to use JSONEditor on TW 5.1.21 + Node.js, loading plugins via `tiddlywiki.info` (Windows 10).

- Minified plugin.info file provided at the release page is for rel 0.0.5, while on the demo page I see rel. 0.0.6 is loaded

- Plugin.info provided at the release page looks empty once it is loaded. I had a closer look and noticed that in the included json the shadow tiddlers are wrapped in an object named "text", while it should be "tiddlers"

- Changing the object name to tiddlers it raises the following error while loading:

```
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
z:\opt64\tw5.1.21\boot\boot.js:99
                        array.push.apply(array,value);
                                   ^

RangeError: Maximum call stack size exceeded
    at Object.$tw.utils.pushTop (z:\opt64\tw5.1.21\boot\boot.js:99:15)
    at $:/core/modules/filters.js:249:17
    at $:/core/modules/filters.js:285:4
    at Object.$tw.utils.each (z:\opt64\tw5.1.21\boot\boot.js:126:12)
    at $tw.Wiki.filterFunction ($:/core/modules/filters.js:284:13)
    at $tw.Wiki.exports.filterTiddlers ($:/core/modules/filters.js:171:12)
    at SetWidget.getValue ($:/core/modules/widgets/set.js:78:27)
    at SetWidget.execute ($:/core/modules/widgets/set.js:51:37)
    at SetWidget.render ($:/core/modules/widgets/set.js:32:7)
    at ElementWidget.Widget.renderChildren ($:/core/modules/widgets/widget.js:390:15)
```

Node.js crashes soon after the error is raised.

- I tried to build minified plugin.info rel. 0.0.6, starting from the tid file downloaded from your demo site (I did it with many other plugins and it always worked). It raises the following errors while loading:

```
Serving on http://127.0.0.1:8080
(press ctrl-C to exit)
 syncer-server-filesystem: Dispatching 'save' task: $:/StoryList
Error executing boot module $:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js: {}

$:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js:24
if (!Element.prototype.closest) {
^

ReferenceError: Element is not defined
    at $:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js:24:1
    at $:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js:509:3
    at Script.runInContext (vm.js:130:20)
    at Script.runInNewContext (vm.js:136:17)
    at Object.runInNewContext (vm.js:319:38)
    at Object.$tw.utils.evalSandboxed (z:\opt64\tw5.1.21\boot\boot.js:518:5)
    at Object.$tw.modules.execute (z:\opt64\tw5.1.21\boot\boot.js:794:15)
    at z:\opt64\tw5.1.21\boot\boot.js:834:30
    at Object.$tw.utils.each (z:\opt64\tw5.1.21\boot\boot.js:135:12)
    at Object.$tw.modules.forEachModuleOfType (z:\opt64\tw5.1.21\boot\boot.js:833:12)
```

Still Node.js crashes soon after the error is raised.

Dragging plugins from your demo site to a fresh single page 5.1.21 empty.html, they are loaded without problems.

I gave up. I would really appreciate if I could experiment with your JSONEditor plugin, but it would be not very useful for my use case, if I could not use it in a Node.js environment.

Thanks in advance for your help. Best regards, 

)+(

**Comment by joshuafontany** [comment]
Thanks for this. I develop on Node.js with Bob, so that is a bit weird. Possibly just an error in packaging (I did put that last release together in the middle of recovering from a HDD failure). Just got my laptop IDE back up and going, so I'll be able to check into it this week.

**Comment by mauloop** [comment]
It looks weird to me as well. While waiting for the result of your check I run one more test. I created a new empty Node.js based wiki, which loads all of the required plugins via tiddlywiki.info, but JSONEditor plugin.

```
...
    "plugins": [
        "tiddlywiki/tiddlyweb",
        "tiddlywiki/filesystem",
        "TheDiveO/FontAwesome",
	"ebalster/modloader",
	"@oss/bootstrap4",
	"matabele/action-maketid",
	"joshuafontany/jsonmangler"
    ],
...
```

It started succesfully. Then I dragged JSONEditor plugin rel. 0.0.6 link from your demo to my wiki... et voila'!!! everything worked as expected. I also copied all of the examples provided in the demo and they worked too.

So everything make me convinced that the key is in the packaged version. Attached to this post you will find the plugin.info based on rel. 0.0.6 that I packaged on  my own.

I hope all of this will help. Regards,

)+(

[plugin.zip](https://github.com/joshuafontany/TW5-jsoneditor/files/3673213/plugin.zip)

**Comment by mauloop** [comment]
My last update was a false hope. Dragging the plugin link to the wiki:

- it works after the page is reloded
- it stops to work after the node.js server is restarted

Restarting node.js it still crashes displaying the usual ReferenceError messages:

```
...
Error executing boot module $:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js: {}

$:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js:24
if (!Element.prototype.closest) {
^

ReferenceError: Element is not defined
    at $:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js:24:1
    at $:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js:509:3
    at Script.runInContext (vm.js:130:20)
    at Script.runInNewContext (vm.js:136:17)
    at Object.runInNewContext (vm.js:319:38)
    at Object.$tw.utils.evalSandboxed (z:\opt64\tw5.1.21\boot\boot.js:518:5)
    at Object.$tw.modules.execute (z:\opt64\tw5.1.21\boot\boot.js:794:15)
    at z:\opt64\tw5.1.21\boot\boot.js:834:30
    at Object.$tw.utils.each (z:\opt64\tw5.1.21\boot\boot.js:135:12)
    at Object.$tw.modules.forEachModuleOfType (z:\opt64\tw5.1.21\boot\boot.js:833:12)
...
```

I tried to raise the plugin-priority to 200 (higher than any other plugin, to be sure it would be loaded last) but it didn't solve.

**Comment by joshuafontany** [comment]
:facepalm: This was a weird one, but somehow my data-recovery caught a snapshot of when I had moved this off to its own plugin, or cross file titles, or something weird. The *.meta file for the json-editor.js file was wrong and read:

title: $:/plugins/joshuafontany/jsonmangler/modules/libs/jsoneditor-widget.js

Instead of:

title: $:/plugins/joshuafontany/jsoneditor/jsoneditor-widget.js

And then I needed to build each plugin.info file correctly.... Still looking at a way to automate that...


...

Anyway, this SEEMS all fixed. I have created a new 0.0.6 release with the correct plugin.info files (not going to advance the version for now). I have included all the required files from JsonMangler so no need to install those separately (note: those minified plugin.info got fixed up too).
https://github.com/joshuafontany/TW5-jsoneditor/releases/tag/0.0.6

Any testing would be appreciated.

Best, Joshua F

**Comment by mauloop** [comment]
Yippee! This is a great news. I noticed that one of the tiddlers had a strange pathname, but I thought it was intentional. I'm going to test it immediately.
Thank a lot.

P.S.: despite JsonMangler is no more required to install JsonEditor, can I still install both in the same wiki?

**Comment by joshuafontany** [comment]
Excuse my previous vague instructions. The Zip file on the JsonEditor
release tab contains plugin.info files in the right folders for all
required plugins (both jsonmangler & jsoneditor) to simplify that style's
install. Everything needed to test it is there in one zip.

**Comment by mauloop** [comment]
I'm sorry to say that 0.0.6 doesn't fix the bug. 

```
Error executing boot module $:/plugins/joshuafontany/jsoneditor/jsoneditor-widget.js: {}

$:/plugins/joshuafontany/jsoneditor/jsoneditor-widget.js:24
if (!Element.prototype.closest) {
^

ReferenceError: Element is not defined
    at $:/plugins/joshuafontany/jsoneditor/jsoneditor-widget.js:24:1
    at $:/plugins/joshuafontany/jsoneditor/jsoneditor-widget.js:509:3
    at Script.runInContext (vm.js:127:20)
    at Script.runInNewContext (vm.js:133:17)
    at Object.runInNewContext (vm.js:299:38)
    at Object.$tw.utils.evalSandboxed (z:\opt64\tw5.1.21\boot\boot.js:518:5)
    at Object.$tw.modules.execute (z:\opt64\tw5.1.21\boot\boot.js:794:15)
    at z:\opt64\tw5.1.21\boot\boot.js:834:30
    at Object.$tw.utils.each (z:\opt64\tw5.1.21\boot\boot.js:135:12)
    at Object.$tw.modules.forEachModuleOfType (z:\opt64\tw5.1.21\boot\boot.js:833:12)
```

I tried to patch `jsoneditor-widget.js` as suggested by @ento in #3. It worked. Loading the wiki did not raise the error any more. I imported all of the examples and CSS from your demo wiki and they look as if they are working as expected.

Hope this will help. Waiting for 0.0.7 (license to poly-kill :)))
